[tox]
toxworkdir = cache/.tox
envlist =
    {%- if cookiecutter.supported_python_version == ">=3.10" %}
    py{310,311,312,313,314}{% endif %}
    {%- if cookiecutter.supported_python_version == ">=3.11" %}
    py{311,312,313,314}{% endif %}
    {%- if cookiecutter.supported_python_version == ">=3.12" %}
    py{312,313,314}{% endif %}
	{%- if cookiecutter.supported_python_version == ">=3.13" %}
    py{313,314}{% endif %}
	{%- if cookiecutter.supported_python_version == ">=3.14" %}
    py{314}{% endif %}
	linter

[testenv]
deps =
    -r requirements/test.txt
commands =
    pip install -e .
    {% if cookiecutter.use_pytest == 'y' -%}
    pytest .
    {%- else -%}
    unittest .
    {%- endif %}

[testenv:linter]
deps =
    -r requirements/test.txt
commands =
    {%- if cookiecutter.use_flake8 == 'y' %}
    flake8 src/{{ cookiecutter.pkg_name }}/.{% endif %}
    {%- if cookiecutter.use_black == 'y' %}
    black --check src/{{ cookiecutter.pkg_name }}/.{% endif %}
    {%- if cookiecutter.use_mypy == 'y' %}
    mypy src/{{ cookiecutter.pkg_name }}/.{% endif %}
